# Generated by Django 3.1.3 on 2020-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etkinlik_adi', models.CharField(default='', max_length=20)),
                ('Etkinlik_tanimi', models.CharField(default='', max_length=20)),
                ('Etkinlik_link', models.URLField(max_length=250)),
                ('Etkinlik_img', models.ImageField(upload_to='Etkinlik')),
            ],
        ),
    ]
