# Generated by Django 3.1.3 on 2020-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_Soyad', models.CharField(default='', max_length=20)),
                ('Görevi', models.CharField(default='', max_length=20)),
                ('Team_Foto', models.ImageField(upload_to='Team')),
                ('Twitter_link', models.URLField(max_length=250)),
                ('linked_link', models.URLField(max_length=250)),
            ],
        ),
    ]
