# Generated by Django 3.1.3 on 2020-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Ad_Soyad',
            field=models.CharField(default='', max_length=30),
        ),
    ]
