# Generated by Django 3.1.3 on 2020-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201213_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Ad_Soyad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='Görevi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
